# Generated by Django 4.2.3 on 2023-08-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='addtime',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.CharField(default='incomplete', max_length=30),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
