# Generated by Django 4.2.3 on 2023-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_todomodel_addtime_todomodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
